# Generated by Django 5.0.6 on 2024-07-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/user-default.png', null=True, upload_to='profile_images/'),
        ),
    ]
