# Generated by Django 5.0.6 on 2024-07-07 15:16

import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_location_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.CharField(max_length=500, validators=[profiles.validators.ValidateMinLength(200)]),
        ),
    ]
