# Generated by Django 5.0.6 on 2024-08-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_message_recipient'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(('sender', models.F('recipient')), _negated=True), name='sender_not_recipient'),
        ),
    ]
